### ISSUE TITLE
Schematron test for internal-destination is wrong

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#22]
Current error is: 

internal-destination="d13e15" token should be 'empty' or 'string'. Enumeration token is 'd13e15'.

It is not "empty or string" but "empty string or idref"  

Can we check if referenced id is specified somewhere in the current document?

Spec says:

> 7.23.8 "internal-destination"
> XSL Definition:
> Value:    empty string | <idref>
> Initial:  empty string
> Inherited:    no
> Percentages:  N/A
> Media:    interactive
> <idref>
> Specifies the destination flow object within the formatting object tree. This property allows the destination flow object node to be explicitly specified.

**Comment by tgraham-antenna** [comment]
In `fo.rnc`:

```
internal-destination =
    ## empty string | <idref>
    attribute internal-destination { xsd:IDREF }?
```

The "empty or string" problem is already in #20.
