### ISSUE TITLE
axf:hyphenation-zone is not checked according to documentation

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#28]
In [the documentation](https://www.antennahouse.com/product/ahf60/docs/ahf-ext.html#IDALD2T) it is said:

axf:hyphenation-zone may have values "none | <length>"

and

> It is invalid when 0 or less value is specified.

None of this is currently checked.

The description in the documentation could also be made a little bit clearer. Suggestion:

»The given value defines a distance from the end of the current block. If a word starts within that region, it will not be hyphenated.«

From my POV this seems to be a way of specifying the minimal text length instead of character count before a hyphenation may happen. Do you agree?

**Comment by tgraham-antenna** [comment]
You could also look at `axf:hyphenation-minimum-character-count` (https://www.antennahouse.com/product/ahf63/ahf-ext.html#axf.hyphenation-minimum-character-count).

**Comment by PullFrom** [comment]
The description of that property is a little bit unclear:

> The axf:hyphenation-minimum-character-count specifies the minimum number of the character to hyphenate.

Does this mean the minimum character count of a word or syllable? Or something else?

**Comment by tgraham-antenna** [comment]
Of the word.  Please see the hyphenation sample in https://www.antennahouse.com/antenna1/comprehensive-xsl-fo-tutorials-and-samples-collection/
