### ISSUE TITLE
Jing: value of attribute "axf:float" is invalid…

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#32]
value of attribute "axf:float" is invalid; must be equal to "after", "auto", "auto-move", "auto-next", "before", "bottom", "center", "column", "end", "inside", "keep", "keep-float", "left", "multicol", "next", "none", "normal", "outside", "page", "right", "skip", "start", "top" or "wrap" 

It seems to me the RNG does not take into account that you can have many of these tokens in `axf:float`.

In may testcase the attribute reads: `axf:float="top right page"`

**Comment by tgraham-antenna** [comment]
Thanks.  Now using Schematron to check multi-token values.
