### ISSUE TITLE
Typo in add-on.xml

### ISSUE THREAD

**Issue by HLeeHart** [AntennaHouse/focheck#33]
The URL for the update is:
<xt:location href="https://github.com/AntennaHouse/focheck/releases/download/v0.5.3/focheck-framework-0.5.3.zip"/>
It should be:
<xt:location href="https://github.com/AntennaHouse/focheck/releases/download/0.5.3/focheck-framework-0.5.3.zip"/>

**Comment by tgraham-antenna** [comment]
Sorry.  The typo was in the tag name used to tag the repository.

Retagged now.  Please close this issue once it works for you.
