### ISSUE TITLE
span="all" only effective in fo:flow context

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#35]
As I learned via AH support:

> span="all" behavior in static area's is a known limitation. The
> xsl-fo standard restricts the use of this property to elements that are
> descendants of fo:flow.

So, I assume a warning could be added via Schematron rule.

https://www.w3.org/TR/xsl/#span

**Comment by tgraham-antenna** [comment]
So how many of these are deserve a warning?

````
        <fo:static-content flow-name="xsl-region-before">
            <fo:block-container span="none"></fo:block-container>
            <fo:block-container span="all"></fo:block-container>
            <fo:block-container span="inherit"></fo:block-container>
        </fo:static-content>
````

**Comment by PullFrom** [comment]
Hi Tony, as far as I understand the spec, that would be "none" and "all".

**Comment by tgraham-antenna** [comment]
"none" is the initial value that doesn't cause spanning.  Since `span` has no effect in `fo:static-content`, I added a warning for when the attribute is present.
