### ISSUE TITLE
Add copyright information to axs.rng

### ISSUE THREAD

**Issue by raducoravu** [AntennaHouse/focheck#40]
The comment at the start of the file should be similar to the one in "axf-inherited.rng"

**Comment by raducoravu** [comment]
@tgraham-antenna are you Ok with the proposed change? We plan to release Oxygen 22 in a couple of days and I updated its used focheck framework to focheck 0.7.1.

**Comment by tgraham-antenna** [comment]
Why 0.7.1 and not 0.7.4?  There's been a lot of changes since 0.7.1, including this one:

> Echoing specific error message when expression language syntax error.

**Comment by raducoravu** [comment]
Sorry, I meant 0.7.4. Oxygen 22 will have it included.

**Comment by tgraham-antenna** [comment]
Included in **focheck** 0.7.5.

**Comment by raducoravu** [comment]
Thanks @tgraham-antenna
