### ISSUE TITLE
RNG file "axf.rng" is invalid

### ISSUE THREAD

**Issue by raducoravu** [AntennaHouse/focheck#42]
Validating it in Oxygen I get about 4 validation errors reported related to ID type attributes like:

    an "element" pattern containing an "attribute" pattern with a non-null ID-type must have a name class that contains only "choice" and "name" elements
    conflicting ID-types for attribute "id" from namespace "http://www.w3.org/XML/1998/namespace" of element "flow" from namespace "http://www.w3.org/1999/XSL/Format"

As a suggested fix in **fo.rng** when "anything" is defined, we can exclude elements in the FO namespace:

      <define name="anything">
       <zeroOrMore>
      <choice>
        <element>
          <anyName>
            <except>
              <nsName ns="http://www.w3.org/1999/XSL/Format"/>
            </except>
          </anyName>

and in **axf.rng** in the "define name="non-xsl"" maybe remove those optional attributes:

       <optional>
            <attribute name="id">
              <data type="ID"/>
            </attribute>
          </optional>
          <optional>
            <attribute name="ref-id">
              <data type="IDREF"/>
            </attribute>
          </optional>
          <optional>
            <attribute name="internal-destination">
              <data type="IDREF"/>
            </attribute>
          </optional>

**Comment by tgraham-antenna** [comment]
I have previously spent a lot of time thrashing around trying to avoid errors such as this:

> conflicting ID-types for attribute "id" of element "mspace" from namespace "http://www.w3.org/1998/Math/MathML"

The `id`, etc., attributes had been my best solution. Excluding more namespaces, as you suggest, would make it simpler.

The other problem is that, for reasons that I don't quite remember, `fo.rnc` doesn't include the MathML and SVG schemas and the XSD version is created from `axf.rnc`, so the XSD version doesn't include the MathML and SVG schemas at all.

**Comment by raducoravu** [comment]
Thaks @tgraham-antenna, the "focheck\schema\rng\axf-mathml3-svg11.rng" is valid. There is still a validation error reported by Oxygen if I directly validate "axf.rng", but we are using the former for XSL-FO validation so this should not influence XSL-FO editing in Oxygen:

    System ID: D:\projects\eXml\frameworks\focheck\schema\rng\fo.rng
    Main validation file: D:\projects\eXml\frameworks\focheck\schema\rng\axf.rng
    Engine name: Jing
    Severity: error
    Description: conflicting ID-types for attribute "id" of element "footnote-number" from namespace "http://www.antennahouse.com/names/XSL/Extensions"
    Start location: 4532:18

**Comment by tgraham-antenna** [comment]
> The other problem is that, for reasons that I don't quite remember, `fo.rnc` doesn't include the MathML and SVG schemas

`fo.rnc` doesn't include the MathML and SVG schemas because they are not required by the XSL 1.1 Recommendation.
