### ISSUE TITLE
catalog.xml should explicitly list provided entity files

### ISSUE THREAD

**Issue by kosek** [AntennaHouse/focheck#43]
Current XML catalog `focheck/schema/catalog.xml` redirects all URI starting with `http://www.w3.org/2003/entities/2007/`. However not all entity files living at that location are provided as a part of focheck. This can lead to errors when other resource is referenced, e.g. `http://www.w3.org/2003/entities/2007/w3centities-f.ent` but local copy of file is not present.

Solution is either to copy all .ent files into focheck or explicitly list only entity files that are part of focheck in `catalog.xml`.

**Comment by tgraham-antenna** [comment]
Would the current `catalog.xml` work better?
