### ISSUE TITLE
axf:outline-* are missing at fo:block

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#5]
The documentation in section "Bookmark and Link in PDF Output" states this as an example for a PDF bookmark:

```
<fo:block axf:outline-level="1"
      axf:outline-expand="false"
      axf:outline-title="Table of Contents">
```

| Attribute | Value |
| --- | --- |
| axf:outline-expand | true | false |
| axf:outline-group | <string> |
| axf:outline-level | <number> |
| axf:outline-title | <string> |
| axf:outline-color | <color> |
| axf:outline-font-style | normal | italic |
| axf:outline-font-weight | normal | bold |

**Comment by tgraham-antenna** [comment]
Added in **focheck 0.0.11**.

Antenna House has so many extensions that it's hard to find time to add them all (so pull requests are always welcome).
