### ISSUE TITLE
Absolute positioning properties missing at of:block

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#7]
The properties 
absolute-position, 
top, 
left, 
right, 
bottom
are not allowed but should be.

**Comment by tgraham-antenna** [comment]
The 'Common Relative Position Properties' (http://www.w3.org/TR/xsl/#common-relative-position-properties) are allowed on fo:block (http://www.w3.org/TR/xsl/#fo_block).  I haven't seen that 'absolute-position' works with fo:block.  Please provide a minimal example.

**Comment by PullFrom** [comment]
I can't find an example for absolute-position, so the issue can be closed, thanks!
