### ISSUE TITLE
fo:flow with single fo:wrapper should be legal

### ISSUE THREAD

**Issue by PullFrom** [AntennaHouse/focheck#8]
If I understand the spec, it should be legal to have only a single fo:wrapper inside fo:flow. But the schema complains…

**Comment by tgraham-antenna** [comment]
Now allowed.  `fo:wrapper` now also has three variations in the schema, where which one is used depends on the context, since `fo:wrapper` allows only what its parent FO allows.

Please update your oXygen framework to see.
